# MOUSE
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# go to sleep after 20 min (1*20*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1200000
CONFIG_ZMK_SLEEP=y

# enable soft off
CONFIG_ZMK_PM_SOFT_OFF=y
